spring:
  datasource:
    url: jdbc:mariadb://${testDbIp:127.0.01}/app20220916_2__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${testDbId:root}
    password: ${testDbPw:root}
  jpa:
    hibernate:
      ddl-auto: none